module.exports = {
  CREATE_USER : 'CREATE_USER',
  INIT_USERS : 'INIT_USERS',
  UPDATE_USER: 'UPDATE_USER',

  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAILED : 'LOGIN_FAILED',
  LOG_OFF: 'LOG_OFF',
  LOGIN_UPDATE: 'LOGIN_UPDATE',

  CHANGE_COLOR: 'CHANGE_COLOR',

  INIT_CREWS: 'INIT_CREWS',
  CREATE_CREW: 'CREATE_CREW',
  ADD_USER_TO_CREW: 'ADD_USER_TO_CREW',
}
