module.exports = {
  CREATE_USER : 'CREATE_USER',
  INIT_USERS : 'INIT_USERS',
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAILED : 'LOGIN_FAILED',
  INIT_POSTS : 'INIT_POSTS',
  ADD_POST: 'ADD_POST',
  LOG_OFF: 'LOG_OFF',
  CHANGE_COLOR: 'CHANGE_COLOR',
  INIT_CREWS: 'INIT_CREWS',
  CREATE_CREW: 'CREATE_CREW',
}
